/**
 * generated by Xtext 2.15.0
 */
package xyz.varad.funpl.ui.contentassist;

import xyz.varad.funpl.ui.contentassist.AbstractFunPLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class FunPLProposalProvider extends AbstractFunPLProposalProvider {
}
