/*
 * generated by Xtext 2.15.0
 */
package xyz.varad.funpl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import xyz.varad.funpl.ui.internal.FunplActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FunPLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(FunplActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		FunplActivator activator = FunplActivator.getInstance();
		return activator != null ? activator.getInjector(FunplActivator.XYZ_VARAD_FUNPL_FUNPL) : null;
	}

}
