/**
 * generated by Xtext 2.15.0
 */
package xyz.varad.funpl.funPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Type Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xyz.varad.funpl.funPL.FunPLPackage#getBooleanTypeDefinition()
 * @model
 * @generated
 */
public interface BooleanTypeDefinition extends BasicTypeDefinition {
} // BooleanTypeDefinition
