/**
 * generated by Xtext 2.15.0
 */
package xyz.varad.funpl.funPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xyz.varad.funpl.funPL.FunPLPackage#getExpression()
 * @model interface="true" abstract="true"
 * @generated
 */
public interface Expression extends Statement, TypeInferredElement {
} // Expression
