/**
 * generated by Xtext 2.15.0
 */
package xyz.varad.funpl.funPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xyz.varad.funpl.funPL.ReferenceExpression#getArgumentList <em>Argument List</em>}</li>
 *   <li>{@link xyz.varad.funpl.funPL.ReferenceExpression#getDeclaration <em>Declaration</em>}</li>
 * </ul>
 *
 * @see xyz.varad.funpl.funPL.FunPLPackage#getReferenceExpression()
 * @model
 * @generated
 */
public interface ReferenceExpression extends Expression {
	/**
	 * Returns the value of the '<em><b>Argument List</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Argument List</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Argument List</em>' containment reference.
	 * @see #isSetArgumentList()
	 * @see #unsetArgumentList()
	 * @see #setArgumentList(ArgumentList)
	 * @see xyz.varad.funpl.funPL.FunPLPackage#getReferenceExpression_ArgumentList()
	 * @model containment="true" unsettable="true"
	 * @generated
	 */
	ArgumentList getArgumentList();

	/**
	 * Sets the value of the '{@link xyz.varad.funpl.funPL.ReferenceExpression#getArgumentList <em>Argument List</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Argument List</em>' containment reference.
	 * @see #isSetArgumentList()
	 * @see #unsetArgumentList()
	 * @see #getArgumentList()
	 * @generated
	 */
	void setArgumentList(ArgumentList value);

	/**
	 * Unsets the value of the '{@link xyz.varad.funpl.funPL.ReferenceExpression#getArgumentList <em>Argument List</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isSetArgumentList()
	 * @see #getArgumentList()
	 * @see #setArgumentList(ArgumentList)
	 * @generated
	 */
	void unsetArgumentList();

	/**
	 * Returns whether the value of the '{@link xyz.varad.funpl.funPL.ReferenceExpression#getArgumentList <em>Argument List</em>}' containment reference is set.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return whether the value of the '<em>Argument List</em>' containment reference is set.
	 * @see #unsetArgumentList()
	 * @see #getArgumentList()
	 * @see #setArgumentList(ArgumentList)
	 * @generated
	 */
	boolean isSetArgumentList();

	/**
	 * Returns the value of the '<em><b>Declaration</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Declaration</em>' reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Declaration</em>' reference.
	 * @see #setDeclaration(Declaration)
	 * @see xyz.varad.funpl.funPL.FunPLPackage#getReferenceExpression_Declaration()
	 * @model required="true"
	 * @generated
	 */
	Declaration getDeclaration();

	/**
	 * Sets the value of the '{@link xyz.varad.funpl.funPL.ReferenceExpression#getDeclaration <em>Declaration</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Declaration</em>' reference.
	 * @see #getDeclaration()
	 * @generated
	 */
	void setDeclaration(Declaration value);

} // ReferenceExpression
