/**
 * generated by Xtext 2.15.0
 */
package xyz.varad.funpl.funPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Inferred Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xyz.varad.funpl.funPL.FunPLPackage#getTypeInferredElement()
 * @model interface="true" abstract="true"
 *        annotation="http://www.obeo.fr/dsl/dnc/archetype archetype='Description'"
 * @generated
 */
public interface TypeInferredElement extends EObject {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @model kind="operation"
	 * @generated
	 */
	Type getReturnType();

} // TypeInferredElement
