/**
 * generated by Xtext 2.15.0
 */
package xyz.varad.funpl.funPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Declared Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xyz.varad.funpl.funPL.TypeDeclaredElement#getDeclaredType <em>Declared Type</em>}</li>
 * </ul>
 *
 * @see xyz.varad.funpl.funPL.FunPLPackage#getTypeDeclaredElement()
 * @model interface="true" abstract="true"
 * @generated
 */
public interface TypeDeclaredElement extends TypeInferredElement {
	/**
	 * Returns the value of the '<em><b>Declared Type</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Declared Type</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Declared Type</em>' containment reference.
	 * @see #isSetDeclaredType()
	 * @see #unsetDeclaredType()
	 * @see #setDeclaredType(Type)
	 * @see xyz.varad.funpl.funPL.FunPLPackage#getTypeDeclaredElement_DeclaredType()
	 * @model containment="true" unsettable="true"
	 * @generated
	 */
	Type getDeclaredType();

	/**
	 * Sets the value of the '{@link xyz.varad.funpl.funPL.TypeDeclaredElement#getDeclaredType <em>Declared Type</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Declared Type</em>' containment reference.
	 * @see #isSetDeclaredType()
	 * @see #unsetDeclaredType()
	 * @see #getDeclaredType()
	 * @generated
	 */
	void setDeclaredType(Type value);

	/**
	 * Unsets the value of the '{@link xyz.varad.funpl.funPL.TypeDeclaredElement#getDeclaredType <em>Declared Type</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #isSetDeclaredType()
	 * @see #getDeclaredType()
	 * @see #setDeclaredType(Type)
	 * @generated
	 */
	void unsetDeclaredType();

	/**
	 * Returns whether the value of the '{@link xyz.varad.funpl.funPL.TypeDeclaredElement#getDeclaredType <em>Declared Type</em>}' containment reference is set.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return whether the value of the '<em>Declared Type</em>' containment reference is set.
	 * @see #unsetDeclaredType()
	 * @see #getDeclaredType()
	 * @see #setDeclaredType(Type)
	 * @generated
	 */
	boolean isSetDeclaredType();

} // TypeDeclaredElement
