/**
 * generated by Xtext 2.14.0
 */
package xyz.varad.funpl.funPL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fun Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xyz.varad.funpl.funPL.FunMethod#getParams <em>Params</em>}</li>
 *   <li>{@link xyz.varad.funpl.funPL.FunMethod#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see xyz.varad.funpl.funPL.FunPLPackage#getFunMethod()
 * @model
 * @generated
 */
public interface FunMethod extends FunAbstractElement
{
  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link xyz.varad.funpl.funPL.FunParameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see xyz.varad.funpl.funPL.FunPLPackage#getFunMethod_Params()
   * @model containment="true"
   * @generated
   */
  EList<FunParameter> getParams();

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(FunBlock)
   * @see xyz.varad.funpl.funPL.FunPLPackage#getFunMethod_Body()
   * @model containment="true"
   * @generated
   */
  FunBlock getBody();

  /**
   * Sets the value of the '{@link xyz.varad.funpl.funPL.FunMethod#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(FunBlock value);

} // FunMethod
