/**
 * generated by Xtext 2.14.0
 */
package xyz.varad.funpl.funPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fun Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xyz.varad.funpl.funPL.FunPLPackage#getFunStatement()
 * @model
 * @generated
 */
public interface FunStatement extends EObject
{
} // FunStatement
