/**
 * generated by Xtext 2.14.0
 */
package xyz.varad.funpl.funPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fun Var Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xyz.varad.funpl.funPL.FunVarDeclaration#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see xyz.varad.funpl.funPL.FunPLPackage#getFunVarDeclaration()
 * @model
 * @generated
 */
public interface FunVarDeclaration extends FunAbstractElement, FunStatement
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(FunExpression)
   * @see xyz.varad.funpl.funPL.FunPLPackage#getFunVarDeclaration_Value()
   * @model containment="true"
   * @generated
   */
  FunExpression getValue();

  /**
   * Sets the value of the '{@link xyz.varad.funpl.funPL.FunVarDeclaration#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(FunExpression value);

} // FunVarDeclaration
