/**
 * generated by Xtext 2.14.0
 */
package xyz.varad.funpl.funPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Terminal Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xyz.varad.funpl.funPL.FunPLPackage#getTerminalExpression()
 * @model
 * @generated
 */
public interface TerminalExpression extends Expression
{
} // TerminalExpression
