/**
 * generated by Xtext 2.14.0
 */
package xyz.varad.funpl.scoping;

import xyz.varad.funpl.scoping.AbstractFunPLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class FunPLScopeProvider extends AbstractFunPLScopeProvider {
}
