/*
 * generated by Xtext 2.14.0
 */
package xyz.varad.funpl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xyz.varad.funpl.parser.antlr.internal.InternalFunPLParser;
import xyz.varad.funpl.services.FunPLGrammarAccess;

public class FunPLParser extends AbstractAntlrParser {

	@Inject
	private FunPLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFunPLParser createParser(XtextTokenStream stream) {
		return new InternalFunPLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FunProgram";
	}

	public FunPLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FunPLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
