/*
 * generated by Xtext 2.14.0
 */
package xyz.varad.funpl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FunPLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("xyz/varad/funpl/parser/antlr/internal/InternalFunPL.tokens");
	}
}
