/*
 * generated by Xtext 2.15.0
 */
package xyz.varad.funpl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFunPLScopeProvider extends DelegatingScopeProvider {
}
