/**
 * generated by Xtext 2.14.0
 */
package xyz.varad.funpl.funPL.impl;

import org.eclipse.emf.ecore.EClass;

import xyz.varad.funpl.funPL.FunExpression;
import xyz.varad.funpl.funPL.FunPLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Fun Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FunExpressionImpl extends FunStatementImpl implements FunExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FunExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FunPLPackage.Literals.FUN_EXPRESSION;
  }

} //FunExpressionImpl
