/**
 * generated by Xtext 2.14.0
 */
package xyz.varad.funpl.tests;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.Test;
import org.junit.runner.RunWith;
import xyz.varad.funpl.funPL.FunPLPackage;
import xyz.varad.funpl.funPL.FunProgram;
import xyz.varad.funpl.tests.FunPLInjectorProvider;
import xyz.varad.funpl.validation.FunPLValidator;

@RunWith(XtextRunner.class)
@InjectWith(FunPLInjectorProvider.class)
@SuppressWarnings("all")
public class FunPLValidatorTest {
  @Inject
  @Extension
  private ParseHelper<FunProgram> _parseHelper;
  
  @Inject
  @Extension
  private ValidationTestHelper _validationTestHelper;
  
  @Test
  public void testForwardReference() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("var i = j;");
      _builder.newLine();
      _builder.append("var j = 10;");
      _builder.newLine();
      this._validationTestHelper.assertError(this._parseHelper.parse(_builder), FunPLPackage.eINSTANCE.getDefinitionRef(), 
        FunPLValidator.FORWARD_REFERENCE, 
        "Definition forward reference not allowed: \'j\'");
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("function myFunc()");
      _builder_1.newLine();
      _builder_1.append("{");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("var i = j;");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("var j = 10;");
      _builder_1.newLine();
      _builder_1.append("}");
      _builder_1.newLine();
      this._validationTestHelper.assertError(this._parseHelper.parse(_builder_1), FunPLPackage.eINSTANCE.getDefinitionRef(), 
        FunPLValidator.FORWARD_REFERENCE, 
        "Definition forward reference not allowed: \'j\'");
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
