/**
 * generated by Xtext 2.15.0
 */
package xyz.varad.funpl;

import xyz.varad.funpl.AbstractFunPLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FunPLRuntimeModule extends AbstractFunPLRuntimeModule {
}
