/**
 * generated by Xtext 2.15.0
 */
package xyz.varad.funpl;

import com.google.inject.Injector;
import org.eclipse.emf.ecore.EPackage;
import xyz.varad.funpl.FunPLStandaloneSetupGenerated;
import xyz.varad.funpl.funPL.FunPLPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class FunPLStandaloneSetup extends FunPLStandaloneSetupGenerated {
  public static void doSetup() {
    new FunPLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
  
  @Override
  public void register(final Injector injector) {
    boolean _containsKey = EPackage.Registry.INSTANCE.containsKey(FunPLPackage.eNS_URI);
    boolean _not = (!_containsKey);
    if (_not) {
      EPackage.Registry.INSTANCE.put(FunPLPackage.eNS_URI, 
        FunPLPackage.eINSTANCE);
    }
  }
}
