/**
 * generated by Xtext 2.14.0
 */
package xyz.varad.funpl.ide;

import xyz.varad.funpl.ide.AbstractFunPLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class FunPLIdeModule extends AbstractFunPLIdeModule {
}
